### PR TITLE
Set the static root

### PR DESCRIPTION
**Pull request by bdero**
Set the static root explicitly in `settings.py` (otherwise collectstatic fails silently).

### CODE REVIEW

**Comment by justinabrahms** [comment]
There are no staticfiles being used, afaik. Just skip `collectstatic` alltogether.

**Comment by justinabrahms** [comment]
Ahh. It looks like django-rest-framework does. :+1: on this PR from me. :)

**Comment by bdero** [comment]
@justinabrahms Can you give this PR another look? I added whitenoise for serving static assets directly from uwsgi: https://devcenter.heroku.com/articles/django-assets

Here it is in action: http://ccxcon-ci.herokuapp.com/api/v1/

The build is failing because of pylint. I'm making another PR to fix that. (Won't merge until all is well with pylint)

**Comment by justinabrahms** [comment]
:+1: when passing.

**Comment by bdero** [comment]
Thanks

**Comment by bdero** [comment]
#35 is a dependency of this PR, going to rebase once it's tests pass.

**Pull request merged**
