### PR TITLE
Reset migrations for courses app.

### PR DESCRIPTION
**Pull request by justinabrahms**
This helps solve a problem with having squashed migrations and it
breaking subsequent migrations.

To get back to a reasonable state, run the following commands in
dbshell. _Note_: You may want to dump your data first so you can load it
back in later.

```
DELETE FROM django_migrations WHERE app='courses';
DROP TABLE courses_course, courses_course_instructors, courses_module,
courses_userinfo, courses_edxauthor CASCADE;
```

then re-run migrations.

### CODE REVIEW

**Comment by justinabrahms** [comment]
@bdero

**Comment by pdpinch** [comment]
Is there an issue to go with this?

**Comment by bdero** [comment]
Alright, cloning the environment to give this a shot.

**Comment by bdero** [comment]
OK, I tested this PR roughly like so:

```
# Clone the ccxcon-ci environment
heroku fork --from ccxcon-ci --to ccxcon-test-db-wipe

# Dump the data from ccxcon-ci
heroku run "python manage.py dumpdata -e contenttypes.contenttype" -a ccxcon-ci > ccxcon-ci-dump.json

# Wipe the database in the new environment
heroku pg:reset DATABASE_URL -a ccxcon-test-db-wipe --confirm ccxcon-test-db-wipe

# Clone the environment
heroku git:clone -a ccxcon-test-db-wipe
cd ccxcon-test-db-wipe

git remote add origin git@github.com:mitodl/ccxcon.git
git remote update

git checkout master
git merge reset-course-migrations
git push heroku master

# Download and import the dumped data
heroku run "curl -0 \"https://*************************.json\" > ccxcon_ci_dump.json; python manage.py loaddata ccxcon_ci_dump.json" -a ccxcon-test-db-wipe
```

@justinabrahms The data in https://ccxcon-test-db-wipe.herokuapp.com/admin/ looks good to me; it looks the same as ccxcon-ci - let me know if it checks out for you.

**Comment by bdero** [comment]
I'm ready to do this for `ccxcon-ci` after the merge happens and migrations fail. :+1:

**Comment by bdero** [comment]
@pdpinch Why the Needs Review label?

**Comment by pdpinch** [comment]
@bdero sorry about the label weirdness. That's a side-effect of Waffle. I'll have to see if I can get it to change how it maps "Waiting on Author"

**Pull request merged**
