### PR TITLE
rc/0.2.0

### PR DESCRIPTION
**Pull request by pwilkins**
- Added missing release_notes template files.
- Changed to `django-server-status`.
- Added logging message for webhooks with non-200 responses.
- Removed `dredd`, removed unused HTTP methods from API, added unit tests.
- Added generator script for life-like data.
- Implemented receiving JSON on `create-ccx` endpoint.
- Added support for course modules.
- Fixed `requests` installation.
- Added additional logging.
- Incoming requests send uuids, not course ids.
- Included the course/module's instance in webhook.
- disabled SSL being necessary for celery.
- Added status.
- Enabled `redis` in the web container.
- Made webhook fixes.
- Added API endpoint to create ccxs on edX.
- Now fetching module listing through course structure api.

### CODE REVIEW

**Comment by pdpinch** [comment]
@giocalitri @justinabrahms I think this includes the commits you were looking for (namely, `Added support for course modules` and `Now fetching module listing through course structure api`)

Can you confirm?

**Comment by pdpinch** [comment]
@pwilkins I don't understand how this has a merge conflict with the rc branch...

**Comment by pwilkins** [comment]
@pdpinch  I'm looking into that merge conflict now.

**Comment by pdpinch** [comment]
```
Unmerged paths:
  (use "git add <file>..." to mark resolution)

    both added:      RELEASE.rst
    both modified:   ccxcon/settings.py
```

**Comment by pwilkins** [comment]
that makes sense.  it's my doing, in any case.

**Pull request merged**
