### PR TITLE
Added status view

### LINKED ISSUE #29: Application level healthcheck
We should have an application-level heartbeat route which can be used for health checking by monitoring services.

The body of the response should be machine readable and contain:
1. The status of each connected component of the application (databases, external application APIs, etc).
2. The elapsed time for each component health check to complete.

Return status of the health check request:
- 200 if everything is fine.
- 500 if one or more components is in a known degraded state (e.g. connection timed out).

Not strictly required for, but related to #10.

### PR DESCRIPTION
**Pull request by giocalitri**
Fixes #29

### CODE REVIEW

**Comment by justinabrahms** [comment]
I'll say the same thing I said to George.

Instead of copying this code from repo to repo, we should just put it in a python package and take it on as a dependency. This would be generally useful to the community at large and useful for us in particular, as we would benefit from only performing updates in a single place.

**Comment by justinabrahms** [comment]
(also, like I told George, if you feel like this is pressing and we don't have time to deduplicate code, then a begrudging :+1:)

**Comment by giocalitri** [comment]
I'll let @pdpinch decide

**Comment by justinabrahms** [comment]
For his reference:
https://github.com/mitodl/lore/blob/master/status/views.py#L36
https://github.com/mitodl/teachersportal/blob/master/portal/views/status.py#L31

**Comment by pdpinch** [comment]
I thought you guys told me this morning that there actually some significant differences between the ccxcon and teachersportal versions of this -- because of a different range of services that needed to report status?

**Comment by justinabrahms** [comment]
No. They are identical. CCXCon has more checks it will need to do
(including redis checking), but it's a strict superset.

Also, that redis checking is in lore too, iirc.

**Comment by giocalitri** [comment]
@pdpinch The difference is just in the services that are tested in the view.

**Pull request merged**
