### PR TITLE
rc/0.2.0

### LINKED ISSUE #128: v0.2.0 release
- Added missing release_notes template files.
- Changed to `django-server-status`.
- Added logging message for webhooks with non-200 responses.
- Removed `dredd`, removed unused HTTP methods from API, added unit tests.
- Added generator script for life-like data.
- Implemented receiving JSON on `create-ccx` endpoint.
- Added support for course modules.
- Fixed `requests` installation.
- Added additional logging.
- Incoming requests send uuids, not course ids.
- Included the course/module's instance in webhook.
- disabled SSL being necessary for celery.
- Added status.
- Enabled `redis` in the web container.
- Made webhook fixes.
- Added API endpoint to create ccxs on edX.
- Now fetching module listing through course structure api.

@pdpinch

### PR DESCRIPTION
**Pull request by pwilkins**
Release v0.2.0
- [x] Added missing release_notes template files
  [pwilkins](pwilkins@mit.edu)
- [x] Move to django-server-status.
  [Justin Abrahms](justin@abrah.ms)
- [x] Added logging message for webhooks with non-200 responses
  [George Schneeloch](gschneel@mit.edu)
- [x] Removed dredd, removed unused HTTP methods from API, added unit tests
  [George Schneeloch](gschneel@mit.edu)
- [x] Added generator script for life-like data.
  [Justin Abrahms](justin@abrah.ms)
- [x] Implemented receiving JSON on create-ccx endpoint
  [George Schneeloch](gschneel@mit.edu)
- [x] Added support for course modules
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Fixed requests installation
  [George Schneeloch](gschneel@mit.edu)
- [x] Added additional logging
  [Justin Abrahms](justin@abrah.ms)
- [x] Incoming requests send uuids, not course ids.
  [Justin Abrahms](justin@abrah.ms)
- [x] Include the course/module's instance in webhook
  [Justin Abrahms](justin@abrah.ms)
- [x] disable SSL being necessary for celery.
  [Justin Abrahms](justin@abrah.ms)
- [x] Added status
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Enabled redis in the web container
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Webhook fixes.
  [Justin Abrahms](justin@abrah.ms)
- [x] API endpoint to create ccx's on edx
  [Justin Abrahms](justin@abrah.ms)
- [x] Fetch module listing through course structure api
  [Justin Abrahms](justin@abrah.ms)

@pdpinch 
Fixes #128

### CODE REVIEW

**Comment by justinabrahms** [comment]
I can't really confirm most of these without staring at server logs set to maximum debug when issuing requests against the server.

**Comment by noisecapella** [comment]
Without teacher's portal being set up we can't verify any webhooks related issues

**Comment by giocalitri** [comment]
The "Added status" cannot be verified because it has been replaced by other code

"Enabled redis in the web container" cannot be verified because it was just for local development.

**Comment by noisecapella** [comment]
@pwilkins I've checked the rest off

**Pull request merged**
