### PR TITLE
Added quotes to SSL redirect var value

### PR DESCRIPTION
**Pull request by bdero**
There's a deprecation warning about it.

### CODE REVIEW

**Comment by justinabrahms** [comment]
Why is it false locally? We have a working and valid ssl setup which is required for oauth (the primary authentication mechanism) to work.

**Comment by noisecapella** [comment]
Locally we aren't serving HTTP content at all, just HTTPS through port 8077, so there's no point in the redirect. Though setting it to True wouldn't hurt anything

**Comment by justinabrahms** [comment]
Locally you just get a 404. It'd be nice if it would just redirect you to the https variety instead.

**Comment by bdero** [comment]
Setting it to true causes tests to fail on travis currently, since the test requests are http and won't follow redirects.

**Comment by bdero** [comment]
The same thing happened on Teachers Portal, for example: https://travis-ci.com/mitodl/teachersportal/builds/19204888

**Comment by justinabrahms** [comment]
:+1:

**Pull request merged**
